add ui scene etc...
Field-Robotics-Japan/OpenConstructionSimulator pull request #11
Opened 2022-05-21 06:33 UTC by tamago117

# menu等のUI追加，それに伴うシステム管理系追加

# 目的
・複数の重機やステージをゲーム実行後に選択できるようにすること

# やったこと
・重機やステージの設定を変えるsceneを別途追加
→「LogoScreen」，「Title」，「Menu」，「DepatureSetting」
・ゲーム内の設定等を管理するクラスを追加
→「GameSetting.cs」
・前回の設定等の管理，設定の読み込みのためjsonファイルに読み書き
・全ての重機に共通の基底クラス（Vehicle）を追加
![ocs](https://user-images.githubusercontent.com/38370926/169639040-93c2cfcf-35ea-4b1a-a902-fd56a5b2e911.png)

2022-05-23 00:31 UTC, RyodoTanaka commented
@tamago117 
PRありがとうございます！
ROSとの連携機能が前提となるPRだと思うので，
ROSのスクリプト有/無 の両方を備えた Scene ファイルがあればマージできるかと思います．

本件機能について，OCSVehicle等の関連リポジトリにもPRを出して頂けると嬉しいです．

@qoopen0815 
レビューお願いします...！

2022-05-23 00:39 UTC, qoopen0815 commented
承知しました！

2022-05-23 01:16 UTC, tamago117 commented
記述し忘れておりました．
今回追加したsceneは「Assets/OcsSystem/UI_scenes」下にまとめておいてあります．
よろしくおねがいします．

2022-05-23 12:18 UTC, qoopen0815 commented
@tamago117 さん、お久しぶりです。
PRありがとうございます。完成度がグッと上がっていて感動しました（笑）

ファイル数が多いのでコードレビューはしきれませんが、ひと通りプレイさせていただいて気になった点を挙げさせていただきます。ARAV内ですでに確認済みでしたらスルーしてください。

2022-05-23 12:24 UTC, qoopen0815 requested changes
ステージ選択画面ではステージの名前を表示してあげると印象付きやすいと思います。
例えばWarehouse Playground, Empty Field などどうでしょう？

![image](https://user-images.githubusercontent.com/26988372/169818070-a3f3f769-9980-4ff8-920f-c3520c790809.png)

2022-05-23 12:41 UTC, qoopen0815 commented
時間帯の選択画面に関して２点あります。
1. 時間帯を選択する画面ではステージの景観がどんな様子かを見せてあげるといいと思います。
2. 「時間帯＝Timezone 」という表現に違和感があるので他の表現にしたほうがいいかもです。

![image](https://user-images.githubusercontent.com/26988372/169819584-a28d52e8-e2a5-4660-b7e5-14581ba551c1.png)

参考にグランツーリスモのステージ選択画面を載せておきますね。（真似してくれという意図はないです）
GT7では時間帯や天候などをすべてひっくるめて「コンディション」と表現しています。

![グランツーリスモ® 7_20220523213332](https://user-images.githubusercontent.com/26988372/169821117-adc2cd40-bdb1-48ba-a62c-4162d398c7c0.jpg)

2022-05-23 12:57 UTC, qoopen0815 commented
あとバグ報告？になりますが、HayashidaSimのステージを選択しても遊べなかったです😢

2022-05-23 22:43 UTC, qoopen0815 commented
追加予定とのこと承知しました！楽しみにしてます！🙌

2022-05-31 09:53 UTC, tamago117 commented
・fieldの名前を追加する
・時間帯の設定をインタラクトに伝える

以上2点対応しました
また，「機体の選択UIを分かりやすいものに変える」は少し時間がかかっているのでもうしばらくお待ちください
![スクリーンショット 2022-05-31 175312](https://user-images.githubusercontent.com/38370926/171146485-0f951beb-6327-4cfa-82a0-b6325418ca47.jpg)
![スクリーンショット 2022-05-31 175701](https://user-images.githubusercontent.com/38370926/171146519-bd8ac255-49fa-48b8-9a57-a19adf4f9bc8.jpg)

2022-06-04 03:35 UTC, tamago117 commented
@qoopen0815 
重機の選択画面試作してみました．イメージこんな感じでいかがでしょうか？
（レースゲーム等のUIを参考にしてみました　→　https://interfaceingame.com/screenshots/asphalt-9-legends-car-garage/）

![image](https://user-images.githubusercontent.com/38370926/171979703-d9f101a6-4ac2-4c1c-875a-10a5cb0657c3.png)

2022-06-04 03:48 UTC, qoopen0815 commented
大枠はいいと思います！

「select vehicles」に「spawn」の意味を付け足して、ユーザーに画面の目的を明示できるとなおいいと思いますが、今のままでもいいと思います！

2022-06-04 03:51 UTC, qoopen0815 commented
@RyodoTanaka コンフリクト解消すればマージOKだと思いますがどうでしょうか！

2022-06-04 04:42 UTC, tamago117 commented
上記の重機選択の部分をcommit ＆ conflict解消しました
以上指摘いただいた箇所は作業終了したかと思います

2022-06-08 09:59 UTC, RyodoTanaka approved these changes
動作確認しました！
とても良いUIになったと思います！！！

2022-06-08 09:59 UTC, merged